bases:
  - ../../base/
resources:
  - policy/placementbinding-openshift-gitops.yaml
  - policy/policy-openshift-gitops.yaml
  - placementrule-openshift-gitops.yaml
  - subscription-openshift-gitops-apps.yaml

patches:
- path: placementrule-infrastructure-prod-policies.yaml
  target: 
    group: apps.open-cluster-management.io
    version: v1
    kind: PlacementRule 
    name: placementrule-infrastructure-policies
    namespace: openshift-gitops
- path: binding-policy-prod.yaml
  target: 
    group: policy.open-cluster-management.io
    version: v1
    kind: PlacementBinding
    name: binding-policy
    namespace: openshift-gitops
