apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: openshift-gitops-apps-subscription
  namespace: openshift-gitops
  labels:
    app: argocd
    app.kubernetes.io/part-of: argocd
    apps.open-cluster-management.io/reconcile-rate: high
  annotations:
    apps.open-cluster-management.io/deployables: ''
    apps.open-cluster-management.io/git-branch: testing
    apps.open-cluster-management.io/git-current-commit: ''
    apps.open-cluster-management.io/git-path: gitops-manifests/app-resources/prod/projects/default/appset
    apps.open-cluster-management.io/reconcile-option: replace
spec:
  channel: nschannelocpgitops/channelopenshiftgitops
  hooksecretref:
    name: admin-token
  placement:
    placementRef:
      kind: PlacementRule
      name: openshift-gitops-placementrule
