apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placementrule-infrastructure-policies
  namespace: openshift-gitops
spec:
  clusterSelector:
    matchLabels:
      environment: lab
