apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
  namespace: openshift-gitops
spec:
  generators:
  - git:
      repoURL: https://github.com/argoproj/argocd-example-apps
      revision: master
      directories:
      - path: guestbook
  template:
    metadata:
      name: '{{path.basename}}'
      namespace: openshift-gitops
    spec:
      project: guestbook
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
      source:
        repoURL: https://github.com/argoproj/argocd-example-apps
        targetRevision: master
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: guestbook
