apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placementrule-all-clusters
  namespace: openshift-gitops
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchLabels:
      vendor: OpenShift
