apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: channelopenshiftgitops
  namespace: nschannelocpgitops
  labels:
    app:  openshift-gitops
  annotations:
    apps.open-cluster-management.io/reconcile-rate: high
spec:
  type: Git
  pathname: https://github.com/giannisalinetti/rhacm-gitops.git
